services:
  - type: web
    name: mental-health-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: TRANSFORMERS_NO_TF
        value: "1"
      - key: USE_TORCH
        value: "1"
      - key: PYTHON_VERSION
        value: "3.12.0"
